### ISSUE TITLE
Please add more built-in methods for scripts/plugins

### ISSUE THREAD

**Issue by mofazhe** [flawiddsouza/Restfox#118]
I hope to add http request method and md5 (crypto-js) method, currently I want to use them.

Please provide more built-in methods if possible, here are bruno and postman related documents for reference:
https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#using-external-libraries
https://docs.usebruno.com/scripting/inbuilt-libraries

**Comment by flawiddsouza** [comment]
Hi @mofazhe, you can already get the http request method in a plugin:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/3eed8d73-80fb-47e7-8300-1c5f02d7b98a)
Or do you mean you want to make http requests through the plugin?

I've added a new feature, so that you can now import ESM modules from esm.sh or unpkg like so:
```js
import CryptoJS from 'https://esm.sh/crypto-js@4.2.0'

var data = "cat"

// Encrypt
var ciphertext = CryptoJS.AES.encrypt(JSON.stringify(data), 'secret key 123').toString();

// Decrypt
var bytes  = CryptoJS.AES.decrypt(ciphertext, 'secret key 123');
var decryptedData = JSON.parse(bytes.toString(CryptoJS.enc.Utf8));

rf.setEnvVar('decryptedText', decryptedData)
```

This way you can use crypto-js or any other npm library you want. For now I've only tested crypto-js and it seems to be working. There definitely will be npm modules that will not work but for those I'll be adding fixes to the plugin system.

This feature hasn't yet been released for desktop but you can test it at https://restfox.dev

Let me know if you want to see any other methods. I'll add them before the next release.

**Comment by flawiddsouza** [comment]
Making http requests through a plugin is now implemented: https://docs.restfox.dev/plugins/making-http-requests.html.

Not yet released for desktop but you can test it it at https://restfox.dev.

**Comment by flawiddsouza** [comment]
Released in https://github.com/flawiddsouza/Restfox/releases/tag/v0.11.0. Closing this issue. You can message here or in a new issue if you need any other feature in the plugin.
