### ISSUE TITLE
[Feat Request] - Chaining request

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#132]
Hi, I'm coming from the Insomnia world, there is one very useful feat that I'd love to see is https://docs.insomnia.rest/insomnia/chaining-requests. May I know if that would be added in the near future?

Thanks!

**Comment by flawiddsouza** [comment]
Would love to add it. Seems a bit complex to implement. Will look into it.

**Comment by bjsvedin** [comment]
I am going to second this request. I have been using the deprecated no longer supported Insomnium all year, and I can't move away from it without being able to pull values from the response of another request. Restfox has everything I need EXCEPT this. I have searched every other rest client out there and none of them support this feature. My reasoning for wanting this feature is to handle my authentication flows without storing anything sensitive in environment variables that can end up in the git repo. Responses are ignored by default which is great, so pulling sensitive access tokens from the response directly rather than storing it in the environment has been a life saver with Insomnium. If you have a work around for this problem right now please let me know and I'll move to Restfox

**Comment by flawiddsouza** [comment]
Hi @bjsvedin, currently there's no workaround. I'll prioritize this for the coming weeks. Will work on this when I get some time.

**Comment by flawiddsouza** [comment]
Hi, response tag is now implemented that allows you to do the same thing as insomnia:

![image](https://github.com/user-attachments/assets/967c9bc5-5606-4fe6-82de-d131a03a94fa)
![image](https://github.com/user-attachments/assets/064a5340-43f5-4e69-b7ff-3053b454100d)
![image](https://github.com/user-attachments/assets/c580033d-e81d-42b1-bdc1-d3585485f2d9)
![image](https://github.com/user-attachments/assets/65fc2838-01b0-44ff-8ddc-30f689981030)

You can test it at https://restfox.dev.

Will be released for desktop in a day or two.

**Comment by flawiddsouza** [comment]
![image](https://github.com/user-attachments/assets/a2e0abcf-2605-40af-99d3-6b3563aaa86e)
I just added Response Tag as description because I didn't know what else to add there.

![image](https://github.com/user-attachments/assets/d1bcac9d-b916-4afc-b141-0d5c7a9f6d7b)
I don't think there's any other way one can handle this, so I'm not sure what exactly the concern is here. There are no requests, hence the dropdown is empty. Seems reasonable.

![image](https://github.com/user-attachments/assets/4e30e08e-83aa-47b1-88db-533abca37937)
This is because empty JSONPath results in 0 matches on body, hence you get []. To get the full body, you can use:
![image](https://github.com/user-attachments/assets/a2fcc80e-8dae-4f37-aead-f6d23a63a948)
The only reason you get full body in the response panel is because we treat absent of jsonpath as no jsonpath being active and show the full response. In JSONPath, you need to pass $ to get the full body:
![image](https://github.com/user-attachments/assets/07a8109f-db43-4055-8b57-c651cc9e54b2)

**Comment by flawiddsouza** [comment]
1. Sounds good. I'll remove the description.
2. Do you want me to change anything here?
3. Then I'll update it, so we get the full response when jsonpath is empty.

**Comment by flawiddsouza** [comment]
2. The request list will never show the request you're currently in. As a request cannot reference itself. If there was only one request in the collection, that's the reason the request list is empty.

**Comment by bjsvedin** [comment]
Wow! I wasn't expecting you to outright lift the insomnia UI for this, so I am pleasantly surprised. I was expecting the functionality to be added into the script portion of the app. I would have been happy either way. I will give this some tests and set it up in my work flow.

**Comment by bjsvedin** [comment]
I have a few bugs/suggestions to report.

Bug 1:
![image](https://github.com/user-attachments/assets/bb3d408d-b54f-4aae-a3e7-94e2ceffe427)

When you use attribute body and need to wrap the resulting value is quotes this messes up the highlighting for the text following it.

Bug 2:
![image](https://github.com/user-attachments/assets/1c14baa9-5a05-44fa-b760-8f01bc6a4beb)
![image](https://github.com/user-attachments/assets/16bda7ec-8cde-4317-96f6-0d9ee76eab48)

It is possible to insert a response tag and not get the UI button over it, rather it leaves the raw placeholder. This can easily be achieved if there are empty opening and closing placeholder characters.

Suggestion 1:
Allow response tags as an environment variable.

**Comment by flawiddsouza** [comment]
Bug 1: Might be in the same category as https://github.com/flawiddsouza/Restfox/issues/228, so not sure if we can actually fix it without implementing custom syntax highlighting for JSON.

Bug 2: I've pushed some fixes. They're deployed at: https://restfox.dev. Can you check and let me know if they're now resolved?

Suggestion 1: Do you mean, you want to be able to use response tags in environment here?
![image](https://github.com/user-attachments/assets/22b1e287-2e4b-4523-b5be-3030c2e62f72)

Suggestion 2: Sounds like a good idea. Even though it looks the same as insomnia, it's not really the same.
Insomnia: {% response('123', 'body', ...) %}
Restfox: {% response(id='123', attribute='body', ...) %}

**Comment by bjsvedin** [comment]
Yes. For Suggestion 1 that is what I mean by using a response tag as an environment variable.

**Comment by bjsvedin** [comment]
I just tested out the the fix for bug 2, I am not able to recreate it anymore, but it seems another thing broke at the same time. 

I am not able to click save on the dialog for the response tag. If i set it up, then click the X button to close it, then reopen it, the data will still be there. But if I try so send a request i get the error

`Error: Could not resolve tag

response()

at ━>response(...)<━`

**Comment by flawiddsouza** [comment]
> Clicking save does in the responseTag dialog does not close it anymore. It does save, if i then click the X button to close it, then reopen it, the data will still be there. But if I try so send a request i get the error

I'm not able to recreate this issue. I can click save and it closes the dialog. Can you check the chrome devtools console using Ctrl + Shift + i to see if there's any error?

Also, clicking on x will never save the data. When you reopen the tag, it should have original data itself.

If possible, can you export the restfox workspace and attach it here, so I can check.

**Comment by bjsvedin** [comment]
Nvm, I don't have the issue anymore. I think it was a caching issue. I thought I had hard refreshed the page since the last time I used it, but maybe I didn't.

**Comment by lilleman-tw** [comment]
Hi. This rocks! Needed exactly this to chain login + query. Thank you so much!
