### ISSUE TITLE
Using axios lib

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#142]
I know it's hard to tell either node-fetch or axios is better. However, I'd like to see if Restfox also considers using axios as its simplicity and some benefits to list out:

- Axios existed before fetch and some products, projects and tutorials are older. It's rarely worth replacing a key dependency in an old product unless it's actively causing problems; something being newer and shinier isn't a good reason on its own to migrate.
- Axios is backwards compatible with IE11 without needing a polyfill, and fetch polyfills tend to only be a little smaller than the whole Axios library.
- Axios has a lot of nice built-in behaviour like throwing errors on 400 and 500 response codes and auto-parsing JSON; you have to implement this yourself with fetch.
- Axios allows you to easily create dedicated HTTP clients with headers, a partial URL, etc built in so you don't have to supply them every time; you'd have to implement this yourself with fetch. This is incredibly useful if your application needs to talk to multiple APIs.

**Comment by flawiddsouza** [comment]
Hi @kobenguyent, we're not using node-fetch. We're using native fetch (https://developer.mozilla.org/en-US/docs/Web/API/fetch).

Choosing fetch over axios was an intentional choice. There are absolutely no negatives or problems with the current implementation. Unless there's something that can't be implemented with the fetch API, I will not be considering switching to axios. If you check, there's no dependency for fetch in package.json.

There are no plans to support IE11, as Restfox uses a lot of modern features like WASM, CSS grid and so on, that do not work with IE11.

Thanks for the recommendation nonetheless.
