### ISSUE TITLE
http/2 support

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#167]
currently I think we are using node-fetch for making requests. Do we consider another lib like https://github.com/sindresorhus/got?tab=readme-ov-file that supports http/2?

**A Quick Overview of HTTP/2**
HTTP/2 is a new Protocol that is replacing HTTP/1.1 thats currently de-facto standard of web.
Main motivation behind it is Performance.
Its backward compatible. Clients and browsers can use HTTP/1.1 as usual if they don’t support HTTP/2.
With HTTP/2, SSL is recommended for performance reasons, but not compulsory.

**Comment by flawiddsouza** [comment]
Sounds like a good idea. Didn't realize that web-standalone was using node-fetch. We'll have to change it to use https://github.com/nodejs/undici instead of node-fetch, as that's what we use in electron. This is what nodejs itself uses to provide the fetch api. We use the npm installed package as it provides the latest fixes and nodejs itself takes time to upstream the fixes. undici (fetch) seems to have http2 support as noted in this test: https://github.com/nodejs/undici/blob/981fb3d72a4393f77c9f28e3ea2f77dc4cf6e9ad/test/fetch/http2.js#L46. Just need to make some time to implement this. Should be possible with minimal code changes.

undici provides the same Fetch API interface as node-fetch and browser fetch, so that should make things simple.

got seems to also recommend a newer library called ky which implements the Fetch API interface:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/c206b8ee-a8d6-4e53-9c44-f01ab1f1ff5b)

**Comment by flawiddsouza** [comment]
http2 requests are now implemented in electron as of this commit: https://github.com/flawiddsouza/Restfox/commit/42cfb808c58a9f12d50209b528d242a90d659708. web-standalone / docker is still pending.

**Comment by flawiddsouza** [comment]
http2 is now implemented in web standalone / docker as of this commit: https://github.com/flawiddsouza/Restfox/commit/a0e2df3c4d41084068757e35b89ef32288edd758.
