### ISSUE TITLE
Cannot make graghql call due to the pre-setted content-type is application/graphql

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#185]
Cannot make graghql call due to the pre-setted content-type is **application/graphql**
![Screenshot 2024-07-17 at 13 31 02](https://github.com/user-attachments/assets/8e32978d-27fe-49d6-b9a7-4055c826c60e)

It works fine when changing the content-type to **application/json**
![Screenshot 2024-07-17 at 13 34 01](https://github.com/user-attachments/assets/444b1170-cd12-4604-8758-52ecfce2fbc7)

**Comment by flawiddsouza** [comment]
Oh no, I think it's because of your latest PR for body type. It was working fine before.

![image](https://github.com/user-attachments/assets/e43812c7-5e62-4a38-8a7b-bf47c511fadc)

Previously, it was like this:
![image](https://github.com/user-attachments/assets/e4a4a359-fa00-4455-ad00-25b405688d7a)
