### ISSUE TITLE
[FR] - Context menu to request URL input

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#246]
Would be nice to bring context menu to request URL input. There are some useful cases that you could benefit from it like:
- encode/ decode uri which is a very useful thing that we use them quite often

![Screenshot 2024-09-19 at 11 48 58](https://github.com/user-attachments/assets/8db0480f-46b6-4dc5-b92d-aac5abbbd7e4)

**Comment by flawiddsouza** [comment]
On desktop, we can definitely use electron's native integration, to add all these options.

In the browser, the problem is I don't want to override the native context menu, as implementing the native undo, redo, cut, copy, paste and select all context menu options correctly can be quite annoying and we can never do 1 to 1 as the browser does it.

Can you tell me more about the use case for EncodeURIComponent and DecodeURIComponent? Restfox should automatically take care of correctly encoding special characters in query params, params and url.
