### ISSUE TITLE
Restfox empty screen

### ISSUE THREAD

**Issue by manueljeffin** [flawiddsouza/Restfox#29]
When I open the restfox today, I find the screen empty with all my requests gone. Attaching screenshot of dev tools. Could you please help

![image](https://user-images.githubusercontent.com/8822750/203225797-954f47a7-17eb-4103-9c62-b77a78bfc6d1.png)

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/8822750/203225850-6f444bfd-632b-4b11-866d-c46c84983657.png">

**Comment by flawiddsouza** [comment]
Hi, can you expand one of these:
![image](https://user-images.githubusercontent.com/10164500/203239065-1705e821-cc40-4196-9734-b0c526d6bc71.png)

Seems like Restfox is unable to open indexeddb. Can you give me the version of your chrome browser?

**Comment by manueljeffin** [comment]
Chrome version: Version 107.0.5304.110 (Official Build) (x86_64)

![image](https://user-images.githubusercontent.com/8822750/203251060-357149fb-f3f0-45c5-a5ca-4b86ec7ffe7f.png)

<img width="572" alt="image" src="https://user-images.githubusercontent.com/8822750/203251176-5db50349-66bb-41b3-bce1-e028bde74f99.png">

Attempt to create a new ends up in below error

![image](https://user-images.githubusercontent.com/8822750/203251331-1b22b950-9054-41ad-9368-40c59956067c.png)

**Comment by flawiddsouza** [comment]
Thanks. Since you only have only 11.55 GB left, it might actually be space issue. According to this: https://web.dev/storage-for-the-web/#how-much, a website can use 60% of the total disk space. Maybe we're hitting that limit. I assume you do a lot of multipart requests and that might be the reason. Since we store the response & request history of each request, it might be eating a lot of storage. I'll have to add a hard limit on the count of response history stored per request to prevent this issue.

Can you run this js code in chrome devtools on restfox.dev. This will help us find out how much storage has been used and how much is left. We might find our culprit there.
```js
if (navigator.storage && navigator.storage.estimate) {
  const quota = await navigator.storage.estimate();
  // quota.usage -> Number of bytes used.
  // quota.quota -> Maximum number of bytes available.
  const percentageUsed = (quota.usage / quota.quota) * 100;
  console.log(`You've used ${percentageUsed}% of the available storage.`);
  const remaining = quota.quota - quota.usage;
  console.log(`You can write up to ${remaining} more bytes.`);
}
```

The issue can probably be temporarily resolved by freeing some additional disk space.

**Comment by manueljeffin** [comment]
![image](https://user-images.githubusercontent.com/8822750/203261991-d2d0630c-4254-437e-bf5b-9ebc9daea3c8.png)

**Comment by manueljeffin** [comment]
Restarted my system and now things seem fine.

![image](https://user-images.githubusercontent.com/8822750/203263401-2ba69d9a-d906-473d-baed-bf9c290180e9.png)

Lost data though as I cleared site data in browser. Might have to take regular backups from now on. Thanks for the help
