### ISSUE TITLE
WebSockets message/payload area uses "CodeMirror single line" instead of the CodeMirror JSON plugin

### ISSUE THREAD

**Issue by notmuhammad** [flawiddsouza/Restfox#299]
When sending messages through WebSockets, the "Payload" text area does not make use of the CodeMirror JSON plugin and instead uses the single line CodeMirror variant just like the Payload title input field and the request/connection URL input field. The lack of features like auto close braces or quotes, indentation, etc. while typing makes it hard to use this part.

There is a "Beautify JSON" button but it's inconvenient to use.

**Comment by flawiddsouza** [comment]
The reason this is the case is because there's no rule that payload has to be JSON in websocket messages. It can also be non json text or any text for that matter. It's a developer choice. Beautify JSON was kept there for people who would use json.

I can look into adding a new setting, so you can have json editor for websocket payload input. Maybe that would help.

**Comment by notmuhammad** [comment]
Yes, you are absolutely right. It's just a quality of life sort of thing so it's up to you. :)

**Comment by flawiddsouza** [comment]
This is now implemented. No setting needed. Seemed like a good thing to have. You can check it out at: https://restfox.dev. New desktop release will be coming in a week or so.
