### ISSUE TITLE
export environment

### ISSUE THREAD

**Issue by ghost** [flawiddsouza/Restfox#40]
hello, i think this app is a great idea to share same document collection between many devices. what is missing imo is exporting collection together with environment. this would allow to share state of a single api documentation together with all necessary template variables and secrets. is this feature planned? thanks

**Comment by flawiddsouza** [comment]
Hi @pauliusgerve,

![image](https://user-images.githubusercontent.com/10164500/215017651-fe70aef3-5faf-4665-9992-2b5cb44f46c5.png)

I'll look into including the workspace environments when the Export button on the top nav is clicked. I've thought of it before but it wasn't a priority for me. Since there's interest, why not.

**Comment by flawiddsouza** [comment]
Implemented: https://github.com/flawiddsouza/Restfox/commit/bfdfe9ea1df84252f5e465c460e7527cdd143279.
