### ISSUE TITLE
Support for team collaboration

### ISSUE THREAD

**Issue by BoscoDomingo** [flawiddsouza/Restfox#46]
Syncing requests and environments across teams with Git would be an awesome feature. It's keeping me away from using Restfox instead of Postman. This could be easily set up with a GitHub repo Restfox manages and reads from, and all team members must have access to. You simply ask to log in via GitHub and voilá

**Comment by flawiddsouza** [comment]
Definitely want to have sync in Restfox. Sadly haven't been able to come up with a good solution that works well with IndexedDB. This will need some further thinking. Syncing to a repo would be a good feature to have. Thanks for the suggestion.

**Comment by BoscoDomingo** [comment]
Google Drive or Dropbox could also be free alternatives, although they may be a bit more cumbersome. Hope you can get this in soon!

**Comment by matthiasbaldi** [comment]
As an idea: PouchDB has an IndexedDB builtin adapter (https://pouchdb.com/adapters.html).
Then everyone can - if needed - selfhost or use a cloud instance of a CouchDB (or any similar soloution) to sync and share it?
Maybe that would be the smallest effort on the Restfox side.
wdyt?

**Comment by scop** [comment]
Some more food for thought: [Bruno's](https://www.usebruno.com) config dirs look like they're trivially shareable via git, https://docs.usebruno.com/manifesto.html. Quite different approach from IndexedDB though.

**Comment by flawiddsouza** [comment]
> As an idea: PouchDB has an IndexedDB builtin adapter ([pouchdb.com/adapters.html](https://pouchdb.com/adapters.html)). Then everyone can - if needed - selfhost or use a cloud instance of a CouchDB (or any similar soloution) to sync and share it? Maybe that would be the smallest effort on the Restfox side. wdyt?

Hi, this only works if you're using pouchdb from the beginning. IndexedDB adapter does not mean it automatically handles any existing IndexedDB database. It just provides a way to use pouchdb over IndexedDB. I wish it were this simple.

**Comment by flawiddsouza** [comment]
> Some more food for thought: [Bruno](https://www.usebruno.com)'s config dirs look like they're trivially shareable via git, [docs.usebruno.com/manifesto.html](https://docs.usebruno.com/manifesto.html). Quite different approach from IndexedDB though.

This is definitely something I want to have. See my comment here: https://github.com/flawiddsouza/Restfox/issues/47#issuecomment-1646512680. It's a blocker for the web. For electron, we can probably just use the native APIs.

**Comment by cj-scott-prive** [comment]
@flawiddsouza Please note some companies will have Data and Security policies that expressly prohibit storing company secrets into applications capable of "cloud sync".

My team and partners needed to abandon Postman because of cloud sync. I  recommended Restfox due to "Offline-First".

This is a widely discussed feature (problem) on Postman's forums and Postman's Git Issues/Discussions. 

Please consider keeping a version of Restfox which is offline-only (where the user is never given the option of opting in to "convenience" syncing). It is not a matter of whether every user follows local instructions not to click this. If the application supports cloud sync, then it must be uninstalled.

**Comment by flawiddsouza** [comment]
Hi @cj-scott-prive, Restfox will forever be offline first. There will never be a login. Both of those links point to syncing to the external company's servers. I don't think I have the budget or bandwidth to provide a syncing server. Nor is implementing sync a simple endeavor. I eventually plan to add file based collections (that are saved to the pc locally), similar to Bruno, so people can use dropbox or their own git to backup their collections. This would allow for the team collaboration that has been requested in this thread. I want to understand if this is something you're okay with or not since you mention Bruno in your message.

**Comment by cj-scott-prive** [comment]
Hi @flawiddsouza 
Thank you for the super-fast response.

I think "file based" would not cause a conflict with policy. It would not be considered cloud or remote syncing, since Restfox would just see some local directory. An export.

(Then if folks want to layer in their own tooling underneath that directory/filesystem, 
 FUSE or Dropbox etc, it is done outside the scope of Restfox).

Sounds like you're aware of the concern, so thank you for that 
(and once more, thanks for an amazing application). :-)

I completely +1 the notion of file-based improvements. It is always painful to teamwork on (any application's) auto-generated JSON, getting clean diffs, etc. Cheers.
