### ISSUE TITLE
OpenAPI Style Path Parameters

### ISSUE THREAD

**Issue by freddyyeddy** [flawiddsouza/Restfox#51]
currently only :param style path parameters are used for place holding. I propose a setting to choose Postman (:) or OpenAPI ({}) type path parameters

**Comment by flawiddsouza** [comment]
This is now implemented. There's no setting but now you can use both :paramName and {paramName} for parameter substitution.

**Comment by azvyae** [comment]
Apparently, imported Open API path params is treated as environment variables

![image](https://github.com/flawiddsouza/Restfox/assets/44611397/7264964f-3729-4128-baea-5b322acbe971)

**Comment by flawiddsouza** [comment]
Hi @azvyae,

From the official documentation {{ id }} is not a valid openapi query parameter. See:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/d2343ce1-08b3-49d5-a13f-7bf6f7f8f444)
Query parameters should be { id }. Written with a single brace instead of double.

Let me know if something else is happening.

**Comment by flawiddsouza** [comment]
Hi @azvyae,

From the official documentation {{ id }} is not a valid openapi path parameter. See:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/d2343ce1-08b3-49d5-a13f-7bf6f7f8f444)
id parameter should be written as { id }. With a single brace instead of double.

Let me know if something else is happening.

**Comment by azvyae** [comment]
I know but I found that the insomnia-importers package that you use for converting the OpenAPI yaml file did that

![image](https://github.com/flawiddsouza/Restfox/assets/44611397/18c9c5a6-b605-42f9-8144-7c8f468d1dfa)

And seems like they use VARIABLE_SEARCH_VALUE regex to find single curly brackets `{ }` and replace it into dobule curly brackets here, anyway i will create a PR in a minute to address this issue, let see how it goes

**Comment by flawiddsouza** [comment]
Ah I see. So the issue is in the import. We might have to fork the package to fix this.

**Comment by azvyae** [comment]
Hey @flawiddsouza, I just created a PR for that fix, check that out 🫡🫡
