### ISSUE TITLE
Save binary response as file: wrong parsing of "content-disposition" header

### ISSUE THREAD

**Issue by WolfgangHG** [flawiddsouza/Restfox#73]
This is a followup to #49: you added the feature to save a binary response as file.

The "content-disposition" header in my use case is not parsed correctly, it does not seem to handle the case that the header has filenames in different encodings.
This is the header value:
`attachment; filename=annacerrato_vbb_ritratti-02056.jpg; filename*=UTF-8''annacerrato_vbb_ritratti-02056.jpg`

It is not set by myself, but generated by .NET6 code. My service method returns a "Microsoft.AspNetCore.Mvc.FileStreamResult" result, where I set a property "FileName".

And this is the suggested filename in the "save as" dialog:
![image](https://github.com/flawiddsouza/Restfox/assets/138049/51549869-5771-42bd-b5f1-fdeb7cb8fe1c)

**Comment by flawiddsouza** [comment]
@WolfgangHG Should be fixed now. Please check.

**Comment by WolfgangHG** [comment]
@flawiddsouza I wanted to test if with https://restfox.dev/, but every request just shows an error "Request failed". Even a request to "https://www.google.com" does not work (which works with the desktop client of Restfox). Is restfox.dev down?

**Comment by flawiddsouza** [comment]
@WolfgangHG restfox.dev does not run a server. All requests are made through your browser. Due to cors restrictions, all non cors enabled urls will fail. You should be seeing this error:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/fb8fb06b-916a-4bb2-963a-bfe89ef0177b)
A chrome extension or a firefox extension are required to bypass cors restrictions on the browser if you want to test urls like google.com. See: [Chrome](https://chrome.google.com/webstore/detail/restfox-cors-helper/pgoncladmcclnmilkbnmmbldcihdgfnf) | [Firefox](https://addons.mozilla.org/en-US/firefox/addon/restfox-cors-helper/)

**Comment by WolfgangHG** [comment]
Sorry, my error, with the extension it works, and your filename fix also works.

In comment https://github.com/flawiddsouza/Restfox/issues/49#issuecomment-1703866721 you wrote that I could also set a request header "Access-Control-Expose-Headers" instead of using the extension, so I tried this ;-).

**Comment by flawiddsouza** [comment]
> In comment [#49 (comment)](https://github.com/flawiddsouza/Restfox/issues/49#issuecomment-1703866721) you wrote that I could also set a request header "Access-Control-Expose-Headers" instead of using the extension, so I tried this ;-).

You can do this but you also need to add the two main CORS headers along with that. These two:
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: *

But I don't recommend adding this just for Restfox.
