### ISSUE TITLE
Need UI place to fully Copy the Request + Response

### ISSUE THREAD

**Issue by sprive** [flawiddsouza/Restfox#74]
For evidence reasons, I want to Copy the full Request and Response, so that folks can see what I requested, include the date/time header, etc.

To the right of  `| Preview | Header | Request |` could we have a "full/raw" that contains the full transaction?
So I could copy the whole thing in one go.

**Comment by cj-scott-prive** [comment]
If anyone's needing this to troubleshoot API issues, here's a workaround for now

1. This all assumes you have `netcat` or `nc` installed.
2. Open a Terminal, start netcat on a test port: `netcat -lp 10839`
4. Duplicate your RestFox item (we will edit it)
5. In the new item, change your base url to `http://127.0.0.1:10839/` (plus keep rest of your URL path, whatever it was)
6. Now "Send" in Restfox
7. Check terminal, you should have the REAL HTTP headers sent by RestFox. See below.
8. The Restfox request will "hang" since netcat doesn't supply a Response. You can manually cancel the request.


```POST /oauth/token HTTP/1.1
host: 127.0.0.1:10839
connection: keep-alive
my_restfox_header_var: header_var_value
my_restfox_header_var2: header_var_value2
content-type: application/x-www-form-urlencoded
accept: */*
accept-language: *
sec-fetch-mode: cors
user-agent: undici
accept-encoding: gzip, deflate
content-length: 0
```

If you wanted to see the value of vars being sent, this is quick and it works.
For something important you probably should stand up a test server (which can do the same thing, and also actually respond)

**Comment by flawiddsouza** [comment]
This is now implemented: https://github.com/flawiddsouza/Restfox/pull/155.
