### ISSUE TITLE
environment variables don't work in query item value

### ISSUE THREAD

**Issue by odama626** [flawiddsouza/Restfox#78]

**Comment by flawiddsouza** [comment]
Hi @odama626,

I just checked and it worked fine. See:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/ca4b5d4c-3706-4f8a-b8a5-c77707a69adf)
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/db60dae3-165e-4dbe-9728-8f149da7c25b)

Can you please provide an example screenshot of the request where this isn't working?

Make sure there's no spelling mistake and your access variable matches what's defined in the environment. Also the environment variable access syntax is {{variable}} or {{ variable }}. Sometimes you can miss and use {variable}, which won't work.

**Comment by odama626** [comment]
I was messing with webfinger so my query value was 

```
acct:{{ username }}@{{ host }}
```

So I'm guessing full match is working but not interpolation?

**Comment by flawiddsouza** [comment]
Taking your given example, I executed a webfinger request:

![image](https://github.com/flawiddsouza/Restfox/assets/10164500/b871c0ea-c5f8-4adf-912d-4aeca2a92fd0)
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/8d590c0f-165c-4b1a-a414-d54d641a234f)
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/cfe2e9e7-ef71-458d-8966-c109fd4f622e)

As you can see the substitution worked perfectly fine. Can you tell me what the actual issue is? Is the environment variable not getting substituted? Is that the issue? If so, please make sure you've correctly defined the environment variables.

It would really help if you can show me the full request. You can replace any sensitive data with dummy strings when posting here. You can also right click on the request in the sidebar and export it to json for easy sharing.

**Comment by odama626** [comment]
that's odd, I haven't been able to reproduce it on a separate device today, but here is an export where the problem still persists 
[Restfox_2023-11-08.json](https://github.com/flawiddsouza/Restfox/files/13303167/Restfox_2023-11-08.json)

**Comment by flawiddsouza** [comment]
Here's the issue:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/09c74aa4-9921-4b61-83a7-4c61fd05a5d4)
The query params are getting url encoded when they're synced to the url. I've pushed a fixed. That should resolve the above issue. Many thanks for the export. It really helps with things like this.
