### ISSUE TITLE
Request failing without detailed error content

### ISSUE THREAD

**Issue by mathiasayivor** [flawiddsouza/Restfox#80]
I'm trying to test my API with Restfox, but for some reason the request is failing although it's working on other clients. I tried to find the cause of the error, but Restfox does not provide detailed description of the error.

It'd be really helpful to provide detailed error description when requests fail.

**Comment by flawiddsouza** [comment]
What is the platform you're using Restfox on? Windows, Linux, MacOS or Web (https://restfox.dev)?

If on the web, then you need to install a browser extension to bypass cors restrictions. Else, your requests might fail due to CORS restrictions.

![image](https://github.com/flawiddsouza/Restfox/assets/10164500/85c4a20b-50a5-4247-ae4b-da018a4307a5)

When a request fails, 4 possible causes are listed.

Points 3 & 4 can be bypassed using the [Chrome](https://chrome.google.com/webstore/detail/restfox-cors-helper/pgoncladmcclnmilkbnmmbldcihdgfnf) or [Firefox](https://addons.mozilla.org/en-US/firefox/addon/restfox-cors-helper/) extension for Restfox.

If you're using the web version and have already installed the CORS bypass extension, we can debug the issue further.

If you're using one of the windows, linux or macos builds, then you can see the network response / errors using Ctrl + Shift + I to open Dev Tools -> Network tab:

![image](https://github.com/flawiddsouza/Restfox/assets/10164500/b5c9111f-67ef-4abc-a2f8-8b871dbb7eb1)

**Comment by mathiasayivor** [comment]
I'm on Linux

**Comment by flawiddsouza** [comment]
Looks like it's an electron issue. The suggested solution I found online is to disable ssl certificate verification altogether, which seems like a terrible approach. Trying to find alternate solutions. I'm also open to suggestions or any help I can get on this.

**Comment by mathiasayivor** [comment]
IMO, SSL verification may not be necessary because the client is mostly used for API testing and there's not much concern on SSL. In fact, most of the dev servers use some sort of self-signed certificate.

But if there's still concern about security, how about giving users the option to toggle ssl verification (more of like a switch for strict mode)?

**Comment by flawiddsouza** [comment]
Then I guess the course of action would be implement a toggle in settings to disable ssl verification. Should be simple to do. Probably will be done by the end of this week.
